name: lint
run-name: ${{ github.actor }} is linting 🚀
on: [push, pull_request]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Action Lint
        uses: panda0603/lint-action@1.6.3
            
